window:
  padding:
    x: 16
    y: 16

  opacity: 1.0

font:
  size: 16
  normal:
    family: IosevkaTerm NF
    style: Regular

colors:
  primary:
    background: '0x121212'
    foreground: '0xf5f5f5'

import:
 - /home/harun/.cache/wal/colors-alacritty.yml
