import = ["/home/harun/.cache/wal/colors-alacritty.toml"]

[colors.primary]
background = "0x121212"
foreground = "0xf5f5f5"

[font]
size = 16

[font.normal]
family = "IosevkaTerm NF"
style = "Regular"

[window]
opacity = 1.0

[window.padding]
x = 16
y = 16
